# Generated by Django 3.2.7 on 2021-09-17 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('scholarship_profile', models.ImageField(upload_to='images')),
                ('openingtime', models.DateField()),
                ('closingtime', models.DateField()),
                ('program', multiselectfield.db.fields.MultiSelectField(choices=[('Btech', 'Btech'), ('Mtech', 'Mtech'), ('PHD', 'PHD')], max_length=15)),
                ('caste', multiselectfield.db.fields.MultiSelectField(choices=[('Oc', 'Oc'), ('Obc', 'Obc'), ('Sc', 'Sc'), ('St', 'St')], max_length=12)),
                ('branch', multiselectfield.db.fields.MultiSelectField(choices=[('Cse', 'Cse'), ('Ece', 'Ece'), ('Eee', 'Eee'), ('Mech', 'Mech'), ('Chem', 'Chem'), ('Civil', 'Civil'), ('Bio', 'Bio'), ('Mme', 'Mme')], max_length=35)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('Cse', 'Cse'), ('Ece', 'Ece'), ('Eee', 'Eee'), ('Mech', 'Mech'), ('Chem', 'Chem'), ('Civil', 'Civil'), ('Bio', 'Bio'), ('Mme', 'Mme')], max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone_no', models.CharField(max_length=200)),
                ('address', models.TextField(max_length=200)),
                ('student_profile', models.ImageField(upload_to='images')),
                ('program', models.CharField(choices=[('Btech', 'Btech'), ('Mtech', 'Mtech'), ('PHD', 'PHD')], max_length=100)),
                ('caste', models.CharField(choices=[('Oc', 'Oc'), ('Obc', 'Obc'), ('Sc', 'Sc'), ('St', 'St')], max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Application_Status', models.TextField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=100)),
                ('message', models.TextField(default='', max_length=100)),
                ('scholarship', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.scholarship')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
